#+ summary: Returns all the dishes between the given duration mininum and maximum.
#+ endpoint: https://api.krr.triply.cc/datasets/roderick/recepten/services/recepten/sparql
#+ tags:
#+   - dishes
#+ defaults:
#+   - minDuration: 0
#+   - maxDuration: 30

SELECT DISTINCT ?dishName ?img_location WHERE {
  ?dish vocab:dishName ?dishName .
  ?dish vocab:hasImg ?img_location .
  ?dish vocab:duration ?dur .
  BIND (?_maxDuration_integer+0 AS ?maxx)
  BIND (?_minDuration_integer+0 AS ?minn)
  FILTER (?dur <= ?maxx)
  FILTER (?dur >= ?minn)
}
