#+ summary: Returns the ingredients, their quantities (and their specific units of measurement)
#+ endpoint: https://api.krr.triply.cc/datasets/roderick/recepten/services/recepten/sparql
#+ tags:
#+   - ingredients
#+ defaults:
#+   - gerechtnaam: Ham-Kaas Tosti

PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vocab: <https://nimbostratus.nl/vocab/>
PREFIX recept: <http://nimbostratus.nl/recept/>
PREFIX ob: <http://nimbostratus.nl/>

SELECT ?ingredient ?hoeveelheid ?eenheid WHERE {
  ?gerecht vocab:gerechtnaam ?_gerechtnaam .
  ?ingredient_node vocab:gerecht ?gerecht .
  ?ingredient_node vocab:ingredient ?ingredient .
  ?ingredient_node vocab:hoeveelheid ?hoeveelheid .
  ?ingredient_node vocab:eenheid ?eenheid .
}
LIMIT 30
