#+ endpoint: https://api.krr.triply.cc/datasets/roderick/recepten/services/recepten/sparql
#+ tags:
#+   - ingredients
#+ defaults:
#+   - ingredient: Kaas

PREFIX vocab: <https://iisg.amsterdam/vocab/>
PREFIX recept: <http://nimbostratus.nl/recept/>

SELECT ?gerechtnaam WHERE {
  ?gerecht vocab:gerechtnaam ?gerechtnaam .
  ?ingredient_node vocab:gerecht ?gerecht .
  ?ingredient_node vocab:ingredient "Kaas" .
} LIMIT 10
