#+ summary: Returns all the dishes belonging to a specific kitchen (country of origin) and from their subclasses (if those exist).
#+ endpoint: https://api.krr.triply.cc/datasets/roderick/recepten/services/recepten/sparql
#+ tags:
#+   - dishes
#+ defaults:
#+   - kitchen: http://nimbostratus.nl/albanees

PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vocab: <http://nimbostratus.nl/vocab/>
PREFIX recept: <http://nimbostratus.nl/recipe/>
PREFIX ob: <http://nimbostratus.nl/>

SELECT DISTINCT ?dishName ?img_location WHERE {
  ?dish vocab:dishName ?dishName .
  ?dish vocab:dishName ?img_location .
  { ?dish vocab:kitchen ?sub .
    ?sub rdfs:subClassOf ?_kitchen_iri . }
  UNION
  { ?dish vocab:kitchen ?_kitchen_iri . }
}
