#+ summary: Returns all the dishes
#+ endpoint: https://api.krr.triply.cc/datasets/roderick/recepten/services/recepten/sparql
#+ tags:
#+   - dishes

PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vocab: <https://nimbostratus.nl/vocab/>
PREFIX recept: <http://nimbostratus.nl/recept/>
PREFIX ob: <http://nimbostratus.nl/>

SELECT DISTINCT ?gerechtnaam WHERE {
  ?gerecht vocab:dishName ?gerechtnaam .
}
LIMIT 30
